services:
  backend:
    build:
      context: .
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DOCKER_PROFILE: docker_prod
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: chatapp
      APPLICATION_SECURITY_JWT_SECRETKEY: ${JWT_SECRET_KEY}
      APPLICATION_SECURITY_JWT_EXPIRATION: ${JWT_EXPIRATION}
      APPLICATION_SECURITY_JWT_REFRESHTOKEN_EXPIRATION: ${JWT_REFRESH_EXPIRATION}
      APPLICATION_CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
    user: "${UID:-1000}:${GID:-1000}"
    networks:
      - spring-mysql
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${BACKEND_PORT}:8080"
    volumes:
      - ./logs:/logs

  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: projectTracker
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 10s
      retries: 5
      start_period: 30s
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - spring-mysql
    ports:
      - "${DB_PORT}:3306"

volumes:
  db-data: {}

networks:
  spring-mysql: {}
